### PR TITLE
Download docs

### LINKED ISSUE #118: Document download scripts for models
@vnaik60 a question for you!

It seems pretty clear that we're going to have more data on input4MIPs than any one modelling center needs (e.g. you don't need 5 different resolutions of greenhouse gas concentrations, you'll only need one). Hence, our advice to modelling centers will be more nuanced than, "Download all the data".

I was thinking that it would be very helpful if we started a collection of example downloads. I was hoping we could start with your model. 

I think the requirements would be relatively simple. We would need to know, for your model:

- which solar data do you need (answer is probably all)
- which volcanic data do you need (answer is probably all)
- which greenhouse gas data do you need (global-mean for co2, n2o and some equivalent species, maybe 15-degree data for CH4?)
- which emissions do you need (I have no idea on this one)
- etc.

Then, probably it's also helpful to document any post-processing steps which are likely to be used by multiple models. For example, processing Thomas' data onto the wavelengths of interest for your model.

My instinct is to put this documentation in this repository, so we can update it as soon as we have new data landing. It might make more sense to put it elsewhere of course, so open to suggestions!

cc @durack1

### PR DESCRIPTION
**Pull request by znichollscr**
## Description

Closes #118 

## Checklist

Please confirm that this pull request has done the following:

- [x] Documentation added (where applicable)
- [x] Changelog item added to `changelog/`

### CODE REVIEW

**Comment by znichollscr** [comment]
@durack1 I've started here. Feel free to push directly/comment. I'll finish off tomorrow

**Comment by durack1** [comment]
@cecilehannay just pinging you into this PR/thread, so we can make sure that the documentation that we are building answers your questions.. Please feel free to peek at the start - [118-download-examples/docs/usage-data-user/index.md](https://github.com/PCMDI/input4MIPs_CVs/blob/118-download-examples/docs/usage-data-user/index.md) - and see if this is getting close to helping you out

**Comment by cecilehannay** [comment]
Thanks, I will look at this,

**Comment by durack1** [comment]
@znichollscr just added some nits - this is good enough for a first pass, I suggest we merge, and if @cecilehannay has additional queries, we can augment - or feel free to suggest additional additions @cecilehannay!

**Review by durack1 — APPROVED** [review]
Great, start

**Pull request merged**
