### PR TITLE
Update land-use information and database handling scripts and docs

### PR DESCRIPTION
**Pull request by znichollscr**
## Checklist

Please confirm that this pull request has done the following:

- [x] Documentation added (where applicable)
- [x] Changelog item added to `changelog/`

### CODE REVIEW

**Review by durack1 — APPROVED** [review]

**Comment by znichollscr** [comment]
@eleanororourke this will update the web page (in a couple of minutes once it's deployed). The preview is here: https://input4mips-controlled-vocabularies-cvs--127.org.readthedocs.build/en/127/database-views/input4MIPs_delivery-summary_CMIP6Plus.html

**Comment by znichollscr** [comment]
Alrighty @eleanororourke all live here: https://input4mips-controlled-vocabularies-cvs.readthedocs.io/en/latest/database-views/input4MIPs_delivery-summary_CMIP6Plus.html

**Comment by eleanororourke** [comment]
Quick check - should land use be (0850-2024) or (1850-2024)? It is showing currently as 0850-2024

**Comment by znichollscr** [comment]
0850-2024. I'm not sure why, but there data starts in 850 not 1850

**Comment by eleanororourke** [comment]
Ok, 0850-2024 is now on the website!

**Comment by durack1** [comment]
Some of these data are temporally extended as far back as they can go (@znichollscr pushes back to year 0001, @taubry pushes back to 1750) as many are used across MIPs and pre-1850 matters for some of these.. if we can extend these further back, great. The SSTs are imaginary pre-1950s, but the HadISST data extends back to 1850 v2, v1 starts in 1870

**Pull request merged**
