### PR TITLE
Add version flag to CLI

### PR DESCRIPTION
**Pull request by znichollscr**
@durack1 over to you to make sure you can run the scripts and bump to whatever version you want next.

### CODE REVIEW

**Comment by durack1** [comment]
Is it worth adding a check to ensure the version tag isn't ridiculous, or can we trust one another to be well behaved contributors?

If yes, this is what I had before
https://github.com/PCMDI/input4MIPs_CVs/blob/1c7d88eea7dcdb07a950da67d9f6667cae91829f/src/jsonToHtml.py#L47-L63

**Comment by durack1** [comment]
Oh yeah, and while I am at it - automating the update of the version tag on the README.md, this could be useful to add - 
https://github.com/PCMDI/input4MIPs_CVs/blob/b61be801ec464a50d793cd9a414a0ea91dd4960e/src/jsonToHtml.py#L171-L199

And also have to think about tagging - can this be automated too?

**Comment by znichollscr** [comment]
> Is it worth adding a check to ensure the version tag isn't ridiculous, or can we trust one another to be well behaved contributors?

I wouldn't bother right now. We track everything in CI so we'll see straight away if we put a silly version flag in.

**Comment by znichollscr** [comment]
> And also have to think about tagging - can this be automated too?

Yes. I'm happy to do that, but will take a bit more work so I would suggest merge this as is, then make an issue (where we can list all the places we want the version to appear, e.g. README, HTML files, citation file so I can then make sure I get it consistent in all those places)

**Comment by durack1** [comment]
> make an issue (where we can list all the places we want the version to appear, e.g. README, HTML files, citation file so I can then make sure I get it consistent in all those places)

Will create a new issue after breakie (and the 2 telcos this am after that)

**Review by durack1 — APPROVED** [review]

**Pull request merged**
