### PR TITLE
Update HTML generation

### LINKED ISSUE #41: Update HTML files with function
Convert https://github.com/PCMDI/input4MIPs_CVs/blob/main/src/jsonToHtml.py to a function - that accepts a dictionary and a list of keys that will build a HTML table

Datasets
- All
- CMIP6Plus

Source_id
- All

### PR DESCRIPTION
**Pull request by znichollscr**
Closes #41 

@durack1 you should be able to push directly to this branch. I think this should be enough to get you going. Shout out if any questions. I'm going to try and generate a database that includes the OMIP data too (being slow, too many files). I can't add the solar data to the database at the moment because the time_end and time_start entries are not formatted correctly. I can hack around that if needed, but I'd rather not because having bad values in a database is always painful. I will hack around it if you really want me to though.

### CODE REVIEW

**Comment by durack1** [comment]
As this is all work in progress, might be easier just to merge to `main` and iterate on that there - it's broken in main anyway at the moment

Having to create a new branch off main without the other dirs and files in place seems a little weird..

**Comment by durack1** [comment]
the `src/comp.json` above has been deprecated by `main:scripts/esgf.json` - we'll need to ascertain where all these scripts/src go, no point in having two directories

**Comment by znichollscr** [comment]
> the src/comp.json above has been deprecated by main:scripts/esgf.json - we'll need to ascertain where all these scripts/src go, no point in having two directories

Suggestion: nothing that is currently in the repo goes in `src`. Everything we have right now is scripts. `src` is for actual packages, which we don't have (yet).

I'll:

1. update this based on current state of main
2. delete all comp files except for the latest
3. make sure the HTML generation still works
4. add a basic function to merge the metadata (will have to be much more complicated for CMIP6, but one thing at a time)
5. ping you for a review and to merge

That should get us back to a 'sensible' state

**Comment by durack1** [comment]
> 4\. will have to be much more complicated for CMIP6, but one thing at a time

Totally - let's get our new data ducks lined up as a first pass and merge, then backfill, which will require disk/data polling in addition to the ESGF index polling

**Comment by znichollscr** [comment]
Alrighty @durack1 this should now make more sense and be ready for review. A quick note:

- The name for the "esgf_dataset_master_id" key is a guess. Is a master key on the ESGF side actually a thing or have I misinterpreted the `esgf.json` file?

**Comment by durack1** [comment]
This looks great to me, CMIP6Plus is near done.

> * The name for the "esgf_dataset_master_id" key is a guess. Is a master key on the ESGF side actually a thing or have I misinterpreted the `esgf.json` file?

Yeah this is a little duplicative. The most definitive identifier is `id`.

There are 3 identifiers (ids) in the ESGF index (you might remember the old spreadsheet info [here](https://docs.google.com/spreadsheets/d/1vMlMVAnP25GpHcS0B8cyvFvUoTZxlUvxBmFB-PbLDG0/edit?gid=1827170035#gid=1827170035)). This includes `id`, `instance_id`, `master_id` and `title` (the ESGF version of that). The `id` is the most definitive, as it includes the full dataset identifier down to variable level (which gets a little messy with multiple variable files), along with the version (e.g., 20240726) and the data_node where it's published (e.g., esgf-data2.llnl.gov). In the case that the input4MIPs project is replicated, then for e.g. DKRZ would have the same id information **other** than the data_node, and the `replica` key would be `True` (rather than replica=False for the original publication/entry point into ESGF)

> * What is the "xlink" key meant to point to? Is it a list of strings? Or should it just be a single string? The links don't seem to resolve in a web browser, so do we even want to track this in our database?

`xlink` will only be included (or filled) for the CMIP6 data, this is the citation link that DKRZ (@MartinaSt) provided. As it will not be populated (for now), I suggest we keep track of it (harvest it from ESGF index, etc), but ignore it for HTML rendering etc

This looks great. I also made a minor tweak to the `README.md` so will merge with my single commit added

**Comment by znichollscr** [comment]
> Yeah this is a little duplicative. The most definitive identifier is `id`.

Got it, thanks. I tracked esgf_master_id because it is the key used in `esgf.json`. Do you want to track any others here? Or do we not care?

> `xlink` will only be included (or filled) for the CMIP6 data, this is the citation link that DKRZ (@MartinaSt) provided. As it will not be populated (for now), I suggest we keep track of it (harvest it from ESGF index, etc), but ignore it for HTML rendering etc

Ok got it.

**Pull request merged**
