### PR TITLE
Add source ID level HTML view

### LINKED ISSUE #93: Add source_id/overview view for HTML pages
We currently have two very granular views of the data, a [dataset view, with 270 current entries for 3 source_id's registered](https://pcmdi.github.io/input4MIPs_CVs/docs/input4MIPs_datasets_CMIP6Plus.html), and a [files view, with 1253 current entries for 4 source_id's registered](https://pcmdi.github.io/input4MIPs_CVs/docs/input4MIPs_files_CMIP6Plus.html). These are both dense, and having a higher level `source_id` view would be useful, so the information we are manually collating at https://wcrp-cmip.org/cmip7-task-teams/forcings/#forcing_datasets_availability could be viewed on a dynamic page in this repo.

This will likely require a `get_source_id_view` function being added to the [html_generation.py](https://github.com/PCMDI/input4MIPs_CVs/blob/main/python-packages/input4MIPs-CVs/src/input4MIPs_CVs/html_generation.py#L176-L266) file.

### PR DESCRIPTION
**Pull request by znichollscr**
## Checklist

Please confirm that this pull request has done the following:

- [ ] #91 
- [x] Documentation added (where applicable)
- [x] Changelog item added to `changelog/`

Fix #93

### CODE REVIEW

**Comment by durack1** [comment]
again @znichollscr you are a magician, is this good to merge?

**Comment by durack1** [comment]
This looks good to directly, merge with no additional action required on my part - will do in 15, unless I hear back from you

Fix #93

**Comment by durack1** [comment]
@znichollscr looks like I have stuffed up, as the version info was not incremented... I am a little confused how that step folds in, it must be a post-merge process? Or just now a matter of triggering the `Bump version` action?

**Comment by znichollscr** [comment]
> looks like I have stuffed up... Or just now a matter of triggering the `Bump version` action?

Nah we're all good, just trigger the bump version action now and off we go: https://github.com/PCMDI/input4MIPs_CVs/actions/workflows/bump.yaml.

**Comment by znichollscr** [comment]
(We could automate version incrementing in future, but I tend to have lots of MRs so we could quickly end up at 6.5.100 which seems more harmful than helpful to me...)

**Comment by durack1** [comment]
> (We could automate version incrementing in future, but I tend to have lots of MRs so we could quickly end up at 6.5.100 which seems more harmful than helpful to me...)

At this moment I agree with you. For the CMIP6_CVs, which are far more stable, and not iterating daily, I have versioning baked into every commit.. But at this moment with all the iteration to a workable repo, manual is good for now.

Did we want to catch any other loose ends before 6.5.20 is minted?

**Comment by znichollscr** [comment]
> Did we want to catch any other loose ends before 6.5.20 is minted?

I can do the fix to the different variants of abandoned, maybe after that?

**Pull request merged**
