### PR TITLE
Fix up CEDS delivery summary

### LINKED ISSUE #154: anthropogenic emissions tweak - targeting CEDS-CMIP-2025-11-25
@hahsan1 @ssmithClimate, the latest CEDS-CMIP-2024-10-21 data checks out ok, so I've pulled that across into the publication queue. If the supplemental data is available before Monday, I'll try and pull it all down together and get these published in one hit.

Issues to solve:
- [x] Missing `license` global attribute
- [x] Missing `source_version` global attribute (rename dataset_version_number)
- [x] Missing `areacella` variable (grid cell area)
- [x] Missing solid biofuel emissions
- [ ] Update mip_era = CMIP7 (when final version is ready for CMIP7 DECK commencement)

Generate CEDS-PROV-CMIP-2025-XX-YY to catch 202201 to near-present data, CEDS-CMIP-2025-XX-YY for 185001-202112 data

### PR DESCRIPTION
**Pull request by znichollscr**
## Description

Closes #154 

## Checklist

Please confirm that this pull request has done the following:

- [x] Documentation added (where applicable)
- [x] Changelog item added to `changelog/`

### CODE REVIEW

**Review by durack1 — APPROVED** [review]
Looks good to me, will merge

**Comment by durack1** [comment]
@znichollscr I created a check fail, as I reformatted the HTML manually (well with VSCode), so this is a check while it fails could just be merged, but just in case, I will leave merging over to you

**Comment by znichollscr** [comment]
> @znichollscr I created a check fail, as I reformatted the HTML manually (well with VSCode), so this is a check while it fails could just be merged, but just in case, I will leave merging over to you

Ah ok. The HTML is auto-generated, so yes best not to re-format because it breaks the CI.

**Comment by znichollscr** [comment]
If the formatting is really important, let's do that in a follow up

**Comment by durack1** [comment]
> If the formatting is really important, let's do that in a follow up

Format is irrelevant, if it displays correctly, we're done

**Pull request merged**
