### PR TITLE
Update scripts and re-validate database

### PR DESCRIPTION
**Pull request by znichollscr**
## Description

Uses the new input4mips-validation version

## Checklist

Please confirm that this pull request has done the following:

- [x] Documentation added (where applicable)
- [x] Changelog item added to `changelog/`

### CODE REVIEW

**Comment by znichollscr** [comment]
@durack1 just getting ready for CEDS to land. Would be good to merge before we try and pull in that data.

**Comment by znichollscr** [comment]
This is probably the most helpful summary

image

**Comment by znichollscr** [comment]
https://github.com/PCMDI/input4MIPs_CVs/issues/136#issuecomment-2468933594 is the reason for the one UofMD file that doesn't pass

**Review by durack1 — APPROVED** [review]
@znichollscr another too big for me to check everything - so a Wed sync would be good. We also have the new CEDS-CMIP-2024-10-21* data live now, esgf poll should be good to sync at 12 am tonight

**Comment by znichollscr** [comment]
Ok cool. I'll merge this now so we can keep moving and we can discuss Wednesday

**Pull request merged**
