### PR TITLE
Issue94 durack1 add missing license_id for early CMIP6Plus data

### LINKED ISSUE #94: Fix MRI-JRA55-do-1-6-0 license omission - CC BY 4.0
The CMIP6Plus MRI-JRA55-do-1-6-0 dataset has a CC BY 4.0 license assigned, but this is not in our database - we need to correct that
```
(xcd061nctax) bash-4.2$ ncdump -h ../input4MIPs/CMIP6Plus/OMIP/MRI/MRI-JRA55-do-1-6-0/atmos/3hr/
prra/gr/v20240531/prra_input4MIPs_atmosphericState_OMIP_MRI-JRA55-do-1-6-0_gr_195801010130-
195812312230.nc | grep license
                :license = "OMIP boundary condition data produced by MRI is licensed under a Creative Commons
Attribution 4.0 International License (CC BY 4.0; https://creativecommons.org/licenses/by/4.0). Consult
https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing input4MIPs output, including citation
requirements and proper acknowledgment. Further information about this data, including some limitations,
can be found via the further_info_url (recorded as a global attribute in this file). The data producers and
data providers make no warranty, either express or implied, including, but not limited to, warranties of
merchantability and fitness for a particular purpose. All liabilities arising from the supply of the
information (including any liability arising in negligence) are excluded to the fullest extent permitted
by law" ;
```

### PR DESCRIPTION
**Pull request by durack1**
## Description

License IDs are missing for `MRI-JRA55-do-1-6-0`, `PCMDI-AMIP-1-1-9`, `SOLARIS-HEPPA-CMIP-4-2` and `SOLARIS-HEPPA-CMIP-4-3`. This PR adds these back in.

## Checklist

Please confirm that this pull request has done the following:

- [ ] Documentation added (where applicable)
- [x] Changelog item added to `changelog/`

Fix #94

### CODE REVIEW

**Comment by durack1** [comment]
@znichollscr this is the blurb, but I got a little lost as to how I get this to integrate back into the repo contents etc - I will have to learn by doing, with guidance

**Review by znichollscr — COMMENTED** [review]
Looks good @durack1.

I've made 3 PRs which target this branch, to fix the various things that weren't clear/easy:

1. #100 Some pedantry: fixing the CHANGELOG entry 
2. #101 Updating the db and web pages: we can just merge this or we can go through the steps together next time
3. #103 Fixing the comment generation (doesn't actually have much to do with your PR, but it was a good test case so I did it here): you can probably just merge this one

**Comment by durack1** [comment]
@znichollscr looks like we still have a problem here:
```
 `--check-unchanged` flag used and database would be changed if we continued
Database entries not up to date with inputs. Please run `python python-packages/input4MIPs-CVs/src/input4MIPs_CVs/cli/update-database.py --repo-root-dir .` or the equivalent for your machine.
Error: Process completed with exit code 1.
```

**Comment by znichollscr** [comment]
Alrighty @durack1 I'll fix up the conflicts now then merge

**Comment by znichollscr** [comment]
@durack1 all fixed, green so merging. Over to you to bump when you're ready.

**Pull request merged**
