### PR TITLE
Add placeholder for population dataset

### PR DESCRIPTION
**Pull request by znichollscr**
## Checklist

Please confirm that this pull request has done the following:

- [x] Documentation added (where applicable)
- [x] Changelog item added to `changelog/`

### CODE REVIEW

**Comment by znichollscr** [comment]
@durack1 @vnaik60 not ideal to only have a placeholder, but at least this makes clear the current state of play

**Comment by durack1** [comment]
@znichollscr agreed. It would be ideal if we had more details, like someone/institution that was willing to provide this, but agreed if it's anticipated, then best to recognize this and note the vagueness

**Comment by vnaik60** [comment]
More info here https://office.wcrp-cmip.org/Products/Projects/Messages.aspx?prjID=33&id=327#comments (only accessible to the Forcings TT)

**Comment by znichollscr** [comment]
Thanks Vaishali. That link appears to be dead for me, can you copy the key info here?

**Comment by vnaik60** [comment]
Will do once onlyoffice is accessible.

**Comment by znichollscr** [comment]
Back live, I've got the comment now thanks. See #135

**Pull request merged**
