### PR TITLE
Update CEDS delivery date

### PR DESCRIPTION
**Pull request by znichollscr**
## Checklist

Please confirm that this pull request has done the following:

- [x] Documentation added (where applicable)
- [x] Changelog item added to `changelog/`

### CODE REVIEW

**Review by durack1 — CHANGES_REQUESTED** [review]
Very tight allocation of publication - Sasha will be at the ESGF F2F meeting from the 4-8th, and so I would rather identify the week of the 11th as delivery, assuming that Steve et al have these data finalized

**Comment by znichollscr** [comment]
> Very tight allocation of publication - Sasha will be at the ESGF F2F meeting from the 4-8th, and so I would rather identify the week of the 11th as delivery, assuming that Steve et al have these data finalized

Nice, updated

**Review by durack1 — APPROVED** [review]
Let's hope and cross our fingers
@sashakames just FYI

**Comment by znichollscr** [comment]
@ssmithclimate FYI too

**Pull request merged**
