### PR TITLE
Update status of data sets

### PR DESCRIPTION
**Pull request by znichollscr**
## Checklist

Please confirm that this pull request has done the following:

- [x] Documentation added (where applicable)
- [x] Changelog item added to `changelog/`

### CODE REVIEW

**Comment by znichollscr** [comment]
@eleanororourke @vnaik60 I need to check Louise's data once Paul has pulled it down, but, assuming that is good to go, I think this is where things are at now (so CEDS back in the waiting game as they fix up bugs, otherwise mostly unchanged although biomass burning has obviously slid another month now).

**Comment by vnaik60** [comment]
Yep. Anthro and BB emissions and land use now expected to be available in October, hopefully earlier than later.

**Comment by znichollscr** [comment]
Alrighty we can move land-use into the publishing queue (see #123) so I think we're good to merge this once @durack1 has reviewed

**Review by durack1 — APPROVED** [review]
@znichollscr looks good to me.. Progress!

**Comment by eleanororourke** [comment]
@znichollscr would tomorrow (Friday) be suitable for doing the website update with the latest update? I will not be able to do any updates on Tues/Wed next week as the web developer is working on the backend.

**Comment by znichollscr** [comment]
I think it's really up to you. The extra context I have:

- I don't know when exactly land-use data will be published. So, one of two things could happen
    - land-use data is published tomorrow, so you can update tomorrow and all is done
    - land-use data isn't published until next week, so you have to wait until after the backend updates are done before you can update the land-use part of the table with the link to the published data (so you end up updating on, say, Thursday next week). If this happens, then, tomorrow, you could either
        - just include the updates which are already live (https://input4mips-controlled-vocabularies-cvs.readthedocs.io/en/latest/database-views/input4MIPs_delivery-summary_CMIP6Plus.html)
        - do nothing, and just wait until the land-use data is published before updating

**Comment by eleanororourke** [comment]
Thanks @znichollscr - it only takes a few mins so will do an update tomorrow and if necessary just do the land-use one next week.

**Comment by znichollscr** [comment]
Ah ok cool. With that context, I'll just ping you every time we make an update then

**Comment by znichollscr** [comment]
@eleanororourke if you 'watch' the repository, you will also get notifications every time we make a pull request. 

You can watch the repo by going to https://github.com/PCMDI/input4MIPs_CVs and then clicking the buttons shown below

Screenshot 2024-10-03 at 9 41 39 am

Screenshot 2024-10-03 at 9 42 08 am

If this gives you too many emails, you can adjust them to only be notified about certain things. For you, my guess would be that pull requests (and maybe issues) are the most relevant things (docs on adjusting notifications here: https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/viewing-your-subscriptions#diagnosing-why-you-receive-too-many-notifications)

**Comment by vnaik60** [comment]
The landuse data is now online https://github.com/PCMDI/input4MIPs_CVs/issues/123#issuecomment-2391801456. Not showing up just yet on https://input4mips-controlled-vocabularies-cvs.readthedocs.io/en/latest/database-views/input4MIPs_delivery-summary_CMIP6Plus.html

**Comment by durack1** [comment]
@vnaik60 yep this step requires @znichollscr or I to do something, and he's going to hand hold me through the process (so we have some redundancy across us both) tomorrow at 6 am PDT!

**Comment by vnaik60** [comment]
Got it! Thanks @durack1.

**Comment by eleanororourke** [comment]
The website https://wcrp-cmip.org/cmip7-task-teams/forcings/ currently is mirroring https://input4mips-controlled-vocabularies-cvs.readthedocs.io/en/latest/database-views/input4MIPs_delivery-summary_CMIP6Plus.html

Ping me when land use is up and will do over weekend.

**Comment by znichollscr** [comment]
Land use is up: see #127

**Pull request merged**
